<?php
require_once "config.php";
require_once 'session.php';

//$infos[] = "Un message d'information";
//$erreurs[] = "Un message d'erreur";
?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <?php require_once 'section/head.phtml' ?>
    <title>Accueil - Point final</title>
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>

    <div class="max">
        <?php require_once 'section/retroaction.phtml'; ?>

        <div>
                <h2>Bienvenue sur Point final!</h1>
        </div>
        <div class="conteneur-boites">
                <div class="boite-de-contenu">
                    <p>Point final est simplement un site qui répertorie les résultats des parties jouées sur l'arcade du département afin de pouvoir "remettre dans la face" de ses adversaires leurs défaites!</p>
                </div>
        </div>

        <div class="conteneur-boites">
            <div class="boite-de-contenu">test</div>
            <div class="boite-de-contenu">test</div>
            <div class="boite-de-contenu">test</div>
            <div class="boite-de-contenu">test</div>
        </div>
    </div>

    <?php require_once 'section/pied.phtml'; ?>
</body>

</html>