<?php
require_once "config.php";
require_once 'session.php';

$jeuDao = new JeuDao($config);
$partieDao = new PartieDao($config);
$utilisateurDao = new UtilisateurDao($config);

//$infos[] = "Un message d'information";
//$erreurs[] = "Un message d'erreur";
$nbJoueurs = $utilisateurDao->compterJoueurs();
$nbParties = $partieDao->compterParties();
$nbJeux = $jeuDao->compterJeux();
?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <?php require_once 'section/head.phtml' ?>
    <title>Accueil - Point final</title>
</head>

<body>
    <div class="contenu">
        <?php require_once 'section/entete.phtml'; ?>
            <div class="max">
                <?php require_once 'section/retroaction.phtml'; ?>

                <div>
                        <h2>Bienvenue sur Point final!</h2>
                </div>
                <div class="conteneur-boites">
                        <div class="boite-de-contenu">
                            <p>Point final est simplement un site qui répertorie les résultats des parties jouées sur l'arcade du département afin de pouvoir "remettre dans la face" de ses adversaires leurs défaites!</p>
                        </div>
                </div>

                <div class="conteneur-boites">
                    <div class="boite-de-contenu"><h3><?= $nbJoueurs ?></h3><br>Joueurs</div>
                    <div class="boite-de-contenu"><h3><?= $nbJeux ?></h3><br>JEUX</div>
                    <div class="boite-de-contenu"><h3><?= $nbParties ?></h3><br>Parties jouées</div>
                    <div class="boite-de-contenu">test</div>
                </div>
            </div>
        <?php require_once 'section/pied.phtml'; ?>
    </div>
</body>

</html>